version: '3.4'

services:
  postgres:
    container_name: postgresdb
    image: postgres:13.3
    environment:
      POSTGRES_DB: "apidb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secretochka2442"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d apidb"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - docker_db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "scretochka@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "secretochka2442"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./Backups:/Backups
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - docker_db

  api:
    container_name: api
    image: secretochka/api-kursovay:2.0
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
    - "49151:80"
    depends_on:
    - postgres
    networks:
    - docker_db

networks:
  docker_db:
    driver: bridge
